language: java
  
branches:
  only:
    - master
    - stable

addons:
  postgresql: "9.6"
  myql: "5.7"
  apt:
    packages:
    - libmaven-ant-tasks-java
    - postgresql-9.6-postgis-2.3
    - python3
    - python3-pip
#    - python3-docutils    
    
install: true

before_script:
    - psql -c 'create database ili2db;' -U postgres
    - psql -c 'select version();' -d ili2db -U postgres
    - psql -c 'create extension postgis;' -d ili2db -U postgres
    - psql -c 'create extension "uuid-ossp";' -d ili2db -U postgres
    - psql -c 'select postgis_full_version();' -d ili2db -U postgres
    - # dpkg-query -L python3-docutils
    - python3 --version
    - # python3 -m pip install docutils # results in permission denied
    - # virtualenv my_py3 --python=/usr/bin/python3
    - virtualenv -p python3 my_py3
    - source my_py3/bin/activate # to activate the python3 environemt    
    - python -m pip install docutils # use my_py3
    - python -m pip freeze
    - 
script: 
  - # ant -f build-ili2pg.xml jar
  - gradle jar test 
  - gradle ili2mysqlJar ili2mysqlTest -Dmyurl=jdbc:mysql:///ili2db?useSSL=false -Dmyusr=travis
  - gradle ili2pgJar ili2pgTest -Ddburl=jdbc:postgresql:ili2db -Ddbusr=postgres
  - gradle ili2gpkgJar ili2gpkgTest
  - gradle ili2fgdbJar
  - gradle ili2mssqlJar ili2mssqlTest
  - gradle ili2oraJar ili2oraTest
  - gradle -Drst2html=`which rst2html.py` usrdoc testreport ili2mysqlBindist ili2pgBindist ili2fgdbBindist ili2mssqlBindist ili2oraBindist
#after_failure:
#  - cat  build/junitreport/junit-noframes.html
deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Drst2html=`which rst2html.py` -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE upload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gradle -Drst2html=`which rst2html.py` -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' upload
    on:
      branch: stable
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always