language: java

jdk:
  - openjdk8
  
branches:
  only:
    - master
    - stable

services:
  - docker
  - mysql
  - postgresql
  
addons:
  ssh_known_hosts:
  - ftp.interlis.ch
  apt:
    packages:
    - python3
    - python3-pip
    - postgresql-postgis
    - postgresql-postgis-scripts
#    - python3-docutils    
    
install: true

before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker run --name=mssql-test -e 'ACCEPT_EULA=Y' -e 'MSSQL_PID=Developer' -e 'MSSQL_SA_PASSWORD=MsInst2019x' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-CU9-ubuntu-20.04
    - # localhost is "-S ."
    - sleep 30; docker ps -a; docker logs --tail=50 mssql-test; docker exec -it mssql-test  /opt/mssql-tools/bin/sqlcmd -S . -U sa -P MsInst2019x -Q 'SELECT @@VERSION;'
    - docker exec -it mssql-test  /opt/mssql-tools/bin/sqlcmd -S . -U sa -P MsInst2019x -Q 'create database ili2db;'
    - mysql -u root --password="" -e 'SHOW VARIABLES LIKE "%version%";'
    - psql -c 'create database ili2db;' -U postgres
    - psql -c 'select version();' -d ili2db -U postgres
    - psql -c 'create extension if not exists postgis;' -d ili2db -U postgres
    - psql -c 'create extension "uuid-ossp";' -d ili2db -U postgres
    - psql -c 'select postgis_full_version();' -d ili2db -U postgres
    - # dpkg-query -L python3-docutils
    - python3 --version
    - # python3 -m pip install docutils # results in permission denied
    - # virtualenv my_py3 --python=/usr/bin/python3
    - virtualenv -p python3 my_py3
    - source my_py3/bin/activate # to activate the python3 environemt    
    - python -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install docutils
    - python -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install Pygments
    - python -m pip freeze
    - 
script: 
  - # ant -f build-ili2pg.xml jar
  - ./gradlew jar test 
  - ./gradlew ili2mysqlJar ili2mysqlTest -Dmyurl=jdbc:mysql://localhost/ili2db?useSSL=false -Dmyusr=root
  - ./gradlew ili2pgJar ili2pgTest -Ddburl=jdbc:postgresql:ili2db -Ddbusr=postgres
  - ./gradlew ili2gpkgJar ili2gpkgTest
  - ./gradlew ili2fgdbJar
  - ./gradlew ili2mssqlJar ili2mssqlTest "-Ddburl=jdbc:sqlserver://localhost;databaseName=ili2db" -Ddbusr=sa -Ddbpwd=MsInst2019x
  - # ./gradlew ili2oraJar ili2oraTest
  - ./gradlew -Drst2html=`which rst2html.py` usrdoc testreport ili2mysqlBindist ili2pgBindist ili2fgdbBindist ili2mssqlBindist ili2oraBindist
after_failure:
  - cat build/junitreport/junit-noframes.html && sleep 10
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drst2html=`which rst2html.py` -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE uploadArchives
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drst2html=`which rst2html.py` -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' -Ddownloads_pwd=${downloads_pwd} -Ddownloads_usr=jql_downloads -Ddocs_pwd=${docs_pwd} -Ddocs_usr=jql_docs uploadArchives uploadBin uploadDoc
    on:
      branch: stable
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always